apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc-resize-fail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: sample-storageclass-resize