apiVersion: v1
kind: Pod
metadata:
  name: sample-resource-underonly
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      requests:
        memory: 256Mi
        cpu: 200m