apiVersion: app/v1
kind: Deployment
metadata:
  name: sample-resource
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
      resources:
        requests:
          memory: 1024Mi
          cpu: 500m
        limits:
          memory: 2048Mi
          cpu: 1000m 